### ISSUE TITLE
CKEditor / config.startupMode = 'source';

### ISSUE THREAD

**Issue by siramsay** [chishiki/perihelion#21]
`config.startupMode = 'source';` in ckeditor-config.js seems unneeded if you explicitly set Ckeditor to true in config.

Every time you click update the 'source' is shown instead of the WYSIWYG.

**Comment by siramsay** [comment]
https://github.com/chishiki/perihelion/blob/4ef575d48876a8e5509c5064710f1e01fb392c8a/deploy/src/perihelion/assets/js/ckeditor-config.js#L35

**Comment by siramsay** [comment]
Code on branch https://github.com/chishiki/perihelion/blob/ckeditor_config/deploy/src/perihelion/assets/js/ckeditor-config.js

**Comment by chishiki** [comment]
hi @siramsay this was intentional because ckeditor doesn't play well with bootstrap

what happens is:
- if nicely formatted bootstrap content gets opened in ckeditor
- BOOM your markup is all gone
- content now looks like crap when saved and can't be recovered

https://user-images.githubusercontent.com/3631492/125569860-ecb8f646-ad92-49f6-a48e-3936d882abe2.mov

**Comment by chishiki** [comment]
@siramsay don't plan to change this unless we can find a way to make ckeditor play well in bootstrap 4.6

we leave it in there as a service to content editing newbs who can't use HTML but its suboptimal

**Comment by chishiki** [comment]
> config.startupMode = 'source'; in ckeditor-config.js seems unneeded if you explicitly set Ckeditor to true in config,

if `Config::read('ckeditor')` is false the idea is not to use ckeditor at all

**Comment by siramsay** [comment]
Okay, I saw the message but was unsure of what that meant. 

I think you need to set the Editor to allow all HTML, I think it would be a fairly simple config. It's got to do with a filter. In Drupal, you enable or disable this is a UI. 

Maybe it's on this page.
https://ckeditor.com/docs/ckeditor4/latest/guide/dev_allowed_content_rules.html

**Comment by chishiki** [comment]
Cool yeah if you can show me a better way I'm open to it. I like the sound of allowing all HTML tags. I'm not fond of a WYSIWYG overwriting everything.

**Comment by siramsay** [comment]
It has quite fine-grained control.

**Comment by siramsay** [comment]
I have tested this and works will

**Comment by siramsay** [comment]
Still writing at time of closing but here is more notes on CKEditor 
https://github.com/chishiki/perihelion/wiki/configuring-ckeditor
